#!/usr/bin/env node
// inject-secrets.js — reads APP_HMAC_SECRET from environment and writes src/secrets.js
// src/secrets.js is gitignored so the secret is never committed to source control.
//
// Usage before building:
//   Windows PowerShell:  $env:APP_HMAC_SECRET="your_secret" ; npm run build:win
//   Mac/Linux:           APP_HMAC_SECRET="your_secret" npm run build:mac

const fs   = require('fs');
const path = require('path');

const secret = process.env.APP_HMAC_SECRET;

if (!secret) {
  console.error('\n╔══════════════════════════════════════════════════════════╗');
  console.error('║  [inject-secrets] ERROR: APP_HMAC_SECRET not set         ║');
  console.error('║                                                            ║');
  console.error('║  Set it before building:                                  ║');
  console.error('║  PowerShell: $env:APP_HMAC_SECRET="..." ; npm run build:win ║');
  console.error('║  Mac/Linux:  APP_HMAC_SECRET="..." npm run build:mac       ║');
  console.error('╚══════════════════════════════════════════════════════════╝\n');
  process.exit(1);
}

const outPath = path.join(__dirname, '..', 'src', 'secrets.js');
fs.writeFileSync(
  outPath,
  '// AUTO-GENERATED by scripts/inject-secrets.js — gitignored, never commit this file\n' +
  '// Regenerate by running: node scripts/inject-secrets.js\n' +
  'module.exports = { APP_SECRET: ' + JSON.stringify(secret) + ' };\n',
  'utf8'
);

console.log('[inject-secrets] ✓ src/secrets.js written successfully');
